name: DL_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - numpy
  - matplotlib
  - jupyter
  - tqdm
  - opencv
  - pip
  - pip:
    - notebook
